### PR TITLE
Created an English version for the get_nCov2019() function

### PR DESCRIPTION
**Pull request by tungpatrick**
As this is retrieved from a Chinese API and all shown in Chinese, I wanted to make it available in English as well. The English translations for cities and provinces will be updated if newer cases come in.

### CODE REVIEW

**Comment by tungpatrick** [comment]
Default value is Chinese. But if you use `get_nCov2019(lang='en')`, then the Countries, provinces, and cities will be in English.

**Comment by tungpatrick** [comment]
The English translations for the province and cities come from a json file I created manually at: https://github.com/tungpatrick/nCov2019_prov_city_json/blob/master/provinces_and_cities.json

**Comment by tungpatrick** [comment]
If this is fine with you, I could also try the same thing for `load_nCov2019()`

**Comment by GuangchuangYu** [comment]
thanks.

Can we packed the json files in the package? 

Users in China may have problems to read files directly from github.

**Comment by GuangchuangYu** [comment]
pls go ahead for `load_nCov2019()`

**Pull request merged**
